global using Xunit;
global using Xunit.Abstractions;
global using FluentAssertions;
global using FakeItEasy;
global using AutoFixture;
global using AutoFixture.AutoFakeItEasy;
global using AutoFixture.Xunit2;
global using Microsoft.Extensions.Logging;
global using MartinCostello.Logging.XUnit;
